spring:
  application:
    name: swaggerexam
  datasource:
    url: jdbc:mysql://localhost:3306/swaggerdb
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true