spring:
  application:
    name: securityexam

#  security:
#    user:
#      name: carami
#      password: 1234

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liGJd6oGPfPKXKRJ
            client-secret: 9dcfa625e287f4937317e310fbe30b4cde70f5de
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  spring:
    devtools:
      restart:
        enabled: true
server:
  tomcat:
    max-threads: 200
    min-spare-threads: 10


#logging:
#  level:
#    org:
#      springframework:
#        security: trace


jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012