spring:
  application:
    name: springmvc


  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 0





  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**

  thymeleaf:
    cache: false

